# Generated by Django 2.2 on 2019-05-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('total_area', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
