# Generated by Django 2.2 on 2019-05-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190508_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Apartment'),
            preserve_default=False,
        ),
    ]
